/**Advent of Code 2020 Dec 1 Part 1**/

SELECT	DISTINCT(EXPENSE_SUM.EXPAMT1 * EXPENSE_SUM.EXPAMT2) AS EXP_PROD

FROM (

		SELECT	EXP1.EXPENSE_AMT AS EXPAMT1
				,EXP2.EXPENSE_AMT AS EXPAMT2
				,EXP1.EXPENSE_AMT + EXP2.EXPENSE_AMT AS EXP_SUM

		FROM	ADVENT_DEC01_EXPENSE EXP1
				,ADVENT_DEC01_EXPENSE EXP2
		  
		  ) AS EXPENSE_SUM

WHERE EXPENSE_SUM.EXP_SUM = 2020


/**Advent of Code 2020 Dec 1 Part 2**/

SELECT	DISTINCT(EXPENSE_SUM.EXPAMT1 * EXPENSE_SUM.EXPAMT2 * EXPENSE_SUM.EXPAMT3) AS EXP_PROD

FROM (

		SELECT	EXP1.EXPENSE_AMT AS EXPAMT1
				,EXP2.EXPENSE_AMT AS EXPAMT2
				,EXP3.EXPENSE_AMT AS EXPAMT3
				,EXP1.EXPENSE_AMT + EXP2.EXPENSE_AMT + EXP3.EXPENSE_AMT AS EXP_SUM

		FROM	ADVENT_DEC01_EXPENSE EXP1
				,ADVENT_DEC01_EXPENSE EXP2
				,ADVENT_DEC01_EXPENSE EXP3
		  
		  ) AS EXPENSE_SUM

WHERE EXPENSE_SUM.EXP_SUM = 2020



