/**Advent of Code 2020 Dec 02 - Part 1**/

SELECT  SUM(CASE WHEN SPLIT.LETTER_QTY BETWEEN SPLIT.MIN_LETTER_QTY AND SPLIT.MAX_LETTER_QTY
				THEN 1
				ELSE 0
				END ) AS TEST2
		
FROM 
(
SELECT	PASSWORD_TXT
		,CAST(LEFT(PASSWORD_TXT,CHARINDEX('-', PASSWORD_TXT)-1) AS numeric) AS MIN_LETTER_QTY
		,CAST(SUBSTRING(PASSWORD_TXT,CHARINDEX('-', PASSWORD_TXT)+1,CHARINDEX(' ', PASSWORD_TXT)-3) AS numeric) AS MAX_LETTER_QTY
		,SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)-1,1) AS LETTER_TXT
		,SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)+2,999) AS PASSWORD_ONLY_TXT
		,LEN(SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)+2,999)) - 
				LEN(REPLACE(SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)+2,999),SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)-1,1), '')) AS LETTER_QTY



/**		,CHARINDEX('-', PASSWORD_TXT) AS HYPHEN_POS
		,CHARINDEX(' ', PASSWORD_TXT) AS SPACE_POS
		,CHARINDEX(':', PASSWORD_TXT) AS COLON_POS **/
		
FROM	ADVENT_DEC02_PASSWORD ) AS SPLIT


/**Advent of Code 2020 Dec 02 - Part 2**/

SELECT  SUM(CASE	WHEN SPLIT2.POSITION_1_ENTRY = SPLIT2.LETTER_TXT
				THEN CASE	WHEN SPLIT2.POSITION_2_ENTRY = SPLIT2.LETTER_TXT
							THEN 0
							ELSE 1
							END
				ELSE CASE	WHEN SPLIT2.POSITION_2_ENTRY = SPLIT2.LETTER_TXT
							THEN 1
							ELSE 0
							END
				END ) AS TEST2
		
FROM 
(
SELECT	PASSWORD_TXT
		,CAST(LEFT(PASSWORD_TXT, CHARINDEX('-', PASSWORD_TXT)-1) AS numeric) AS POSITION_1
		,CAST(SUBSTRING(PASSWORD_TXT, CHARINDEX('-', PASSWORD_TXT)+1,CHARINDEX(' ', PASSWORD_TXT)-3) AS numeric) AS POSTITION_2
		,SUBSTRING(PASSWORD_TXT, CHARINDEX(':', PASSWORD_TXT)-1,1) AS LETTER_TXT
		,SUBSTRING(PASSWORD_TXT, CHARINDEX(':', PASSWORD_TXT)+2,999) AS PASSWORD_ONLY_TXT
		,SUBSTRING(SUBSTRING(PASSWORD_TXT, CHARINDEX(':', PASSWORD_TXT)+2,999), CAST(LEFT(PASSWORD_TXT, CHARINDEX('-', PASSWORD_TXT)-1) AS numeric), 1) AS POSITION_1_ENTRY
		,SUBSTRING(SUBSTRING(PASSWORD_TXT, CHARINDEX(':', PASSWORD_TXT)+2,999), CAST(SUBSTRING(PASSWORD_TXT, CHARINDEX('-', PASSWORD_TXT)+1,CHARINDEX(' ', PASSWORD_TXT)-3) AS numeric), 1) AS POSITION_2_ENTRY
		,REPLACE(SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)+2,999),SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)-1,1), '') AS REPTEST
		,LEN(SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)+2,999)) - 
				LEN(REPLACE(SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)+2,999),SUBSTRING(PASSWORD_TXT,CHARINDEX(':', PASSWORD_TXT)-1,1), '')) AS LETTER_QTY



/**		,CHARINDEX('-', PASSWORD_TXT) AS HYPHEN_POS
		,CHARINDEX(' ', PASSWORD_TXT) AS SPACE_POS
		,CHARINDEX(':', PASSWORD_TXT) AS COLON_POS **/
		
FROM	ADVENT_DEC02_PASSWORD ) AS SPLIT2